### ISSUE TITLE
Adapter Installation funktioniert nicht

### ISSUE THREAD

**Issue by pixSR** [Schnup89/IOBroker_HABPanel_eq3_Thermostat#1]
Hey, ich wollte gerne deinen Adapter in iobroker einsetzen.
Also Url : https://github.com/Schnup89/ioBroker.eq3-Thermostat über unbekannte quellen importiert.
Leider immer der gleiche Fehler:
$ iobroker url https://github.com/Schnup89/ioBroker.eq3-Thermostat --host raspberrypi --debug

install Schnup89/ioBroker.eq3-Thermostat#0c87229f4142f4928a2b3aba2d3d92fbdacf45ce

NPM version: 6.14.15

npm install Schnup89/ioBroker.eq3-Thermostat#0c87229f4142f4928a2b3aba2d3d92fbdacf45ce --prefix "/opt/iobroker" (System call)

> node-aead-crypto@2.2.1 preinstall /opt/iobroker/node_modules/node-aead-crypto> node lib/preinstall.js

node-aead-crypto not needed on this system, since all ciphers are natively supported

npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.1 (node_modules/node-aead-crypto):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.1 preinstall: `node lib/preinstall.js`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ iobroker.eq3-thermostat@0.0.2updated 1 package in 49.604s

73 packages are looking for funding run `npm fund` for details

host.raspberrypi Cannot install Schnup89/ioBroker.eq3-Thermostat#0c87229f4142f4928a2b3aba2d3d92fbdacf45ce: 0

ERROR: Process exited with code 25

Kannst du mir sagen was hier falsch läuft?
Danke

**Comment by Schnup89** [comment]
Moin,
der Adapter wird seit längerem nicht mehr weiterentwickelt da es eine Sackgasse war bzgl. Error Handling.

Zufälligerweise hab ich gestern Abend einen neuen Versuch gestartet, ich denke hier bin ich in 1-2 Tagen bei einem Ergebnis, also am besten morgen übermorgen nochmal hier vorbeischauen ;)

**Comment by Schnup89** [comment]
Ich hatte in der Tat das gleiche Problem, anscheinend lag es an der Benamung des GIT Repositorys... Habe den Adaptername nach ioBroker kleingeschrieben, jetzt kommt der Fehler nicht mehr. *FacePalm*
Bitte auch in der Github URL den Adapternamen kleinschreiben, dann geht's.

Geht nicht:
https://github.com/Schnup89/ioBroker.eq3-Thermostat
Geht:
https://github.com/Schnup89/ioBroker.eq3-thermostat
